2025-05-27 14:08:00,668 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for internship.localhost
2025-05-27 14:08:00,713 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for internship.localhost
2025-05-27 14:08:00,716 ERROR scheduler Skipped queueing frappe.email.doctype.newsletter.newsletter.send_scheduled_email because it was found in queue for internship.localhost
2025-05-27 14:08:00,718 ERROR scheduler Skipped queueing frappe.automation.doctype.reminder.reminder.send_reminders because it was found in queue for internship.localhost
2025-05-27 14:08:00,726 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for internship.localhost
2025-05-27 14:08:00,731 ERROR scheduler Skipped queueing erpnext.erpnext_integrations.doctype.plaid_settings.plaid_settings.automatic_synchronization because it was found in queue for internship.localhost
2025-05-27 14:08:00,743 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for internship.localhost
2025-05-27 14:08:00,749 ERROR scheduler Skipped queueing hrms.hr.doctype.shift_type.shift_type.update_last_sync_of_checkin because it was found in queue for internship.localhost
2025-05-27 14:08:00,756 ERROR scheduler Skipped queueing hrms.hr.doctype.shift_type.shift_type.process_auto_attendance_for_all_shifts because it was found in queue for internship.localhost
2025-05-27 14:08:00,765 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for internship.localhost
2025-05-27 14:08:00,768 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.collect_project_status because it was found in queue for internship.localhost
2025-05-27 14:08:00,771 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for internship.localhost
2025-05-27 14:08:00,774 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for internship.localhost
2025-05-27 14:08:00,786 ERROR scheduler Skipped queueing hrms.hr.doctype.daily_work_summary_group.daily_work_summary_group.trigger_emails because it was found in queue for internship.localhost
2025-05-27 14:08:00,788 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for internship.localhost
2025-05-27 14:08:00,790 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for internship.localhost
2025-05-27 14:08:00,827 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for internship.localhost
2025-05-27 14:08:00,834 ERROR scheduler Skipped queueing erpnext.utilities.doctype.video.video.update_youtube_data because it was found in queue for internship.localhost
2025-05-27 14:08:00,839 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for internship.localhost
2025-05-27 14:08:00,843 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for internship.localhost
2025-05-27 14:08:00,845 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.project_status_update_reminder because it was found in queue for internship.localhost
2025-05-27 14:08:00,849 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for internship.localhost
2025-05-27 14:08:00,859 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for internship.localhost
2025-05-27 14:08:00,863 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for internship.localhost
2025-06-12 09:08:02,707 ERROR scheduler Skipped queueing erpnext.crm.doctype.email_campaign.email_campaign.set_email_campaign_status because it was found in queue for internship.localhost
2025-06-12 09:08:02,818 ERROR scheduler Skipped queueing erpnext.stock.doctype.serial_no.serial_no.update_maintenance_status because it was found in queue for internship.localhost
2025-06-12 09:56:00,880 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for internship.localhost
2025-06-12 09:56:00,907 ERROR scheduler Skipped queueing erpnext.utilities.doctype.video.video.update_youtube_data because it was found in queue for internship.localhost
2025-06-12 09:56:00,910 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for internship.localhost
2025-06-12 09:56:00,913 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for internship.localhost
2025-06-12 09:56:00,939 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for internship.localhost
2025-06-12 09:56:00,941 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for internship.localhost
2025-06-12 09:56:00,948 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for internship.localhost
2025-07-08 13:56:00,344 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.pull because it was found in queue for internship.localhost
2025-07-08 13:56:00,384 ERROR scheduler Skipped queueing hrms.hr.doctype.interview.interview.send_interview_reminder because it was found in queue for internship.localhost
2025-07-08 13:56:00,392 ERROR scheduler Skipped queueing erpnext.utilities.bulk_transaction.retry because it was found in queue for internship.localhost
2025-07-08 13:56:00,395 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.collect_project_status because it was found in queue for internship.localhost
2025-07-08 13:56:00,398 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for internship.localhost
2025-07-08 13:56:00,401 ERROR scheduler Skipped queueing erpnext.utilities.doctype.video.video.update_youtube_data because it was found in queue for internship.localhost
2025-07-08 13:56:00,405 ERROR scheduler Skipped queueing frappe.utils.global_search.sync_global_search because it was found in queue for internship.localhost
2025-07-08 13:56:00,406 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for internship.localhost
2025-07-08 13:56:00,410 ERROR scheduler Skipped queueing erpnext.accounts.doctype.gl_entry.gl_entry.rename_gle_sle_docs because it was found in queue for internship.localhost
2025-07-08 13:56:00,414 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for internship.localhost
2025-07-08 13:56:00,416 ERROR scheduler Skipped queueing frappe.twofactor.delete_all_barcodes_for_users because it was found in queue for internship.localhost
2025-07-08 13:56:00,418 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for internship.localhost
2025-07-08 13:56:00,420 ERROR scheduler Skipped queueing erpnext.manufacturing.doctype.bom_update_log.bom_update_log.resume_bom_cost_update_jobs because it was found in queue for internship.localhost
2025-07-08 13:56:00,421 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for internship.localhost
2025-07-08 13:56:00,422 ERROR scheduler Skipped queueing erpnext.stock.doctype.repost_item_valuation.repost_item_valuation.repost_entries because it was found in queue for internship.localhost
2025-07-08 13:56:00,424 ERROR scheduler Skipped queueing erpnext.erpnext_integrations.doctype.plaid_settings.plaid_settings.automatic_synchronization because it was found in queue for internship.localhost
2025-07-08 13:56:00,426 ERROR scheduler Skipped queueing erpnext.projects.doctype.project.project.project_status_update_reminder because it was found in queue for internship.localhost
2025-07-08 13:56:00,427 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for internship.localhost
2025-07-08 13:56:00,430 ERROR scheduler Skipped queueing frappe.core.doctype.prepared_report.prepared_report.expire_stalled_report because it was found in queue for internship.localhost
2025-07-08 13:56:00,434 ERROR scheduler Skipped queueing frappe.desk.form.document_follow.send_hourly_updates because it was found in queue for internship.localhost
2025-07-08 13:56:00,445 ERROR scheduler Skipped queueing frappe.website.doctype.web_page.web_page.check_publish_status because it was found in queue for internship.localhost
2025-07-08 13:56:00,448 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for internship.localhost
2025-07-11 12:40:01,245 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1428, in get_connection
    if connection.can_read() and self.cache is None:
       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 570, in can_read
    return self._parser.can_read(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 79, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 90, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1432, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 12:44:00,840 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 12:48:01,094 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 12:52:00,242 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 12:56:00,425 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 13:00:00,630 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 13:04:00,806 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 13:08:01,001 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 13:12:00,236 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 15:07:15,675 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 15:08:00,822 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 357, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 358, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 730, in _connect
    raise err
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 718, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 71, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 93, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 663, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 668, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 674, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 670, in fetch
    job.refresh()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/job.py", line 1033, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/commands/core.py", line 4978, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 559, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 565, in _execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 1422, in get_connection
    connection.connect()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 363, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:11000. Connection refused.
2025-07-11 15:12:03,567 ERROR scheduler Exception in Enqueue Events for Site internship.localhost
Traceback (most recent call last):
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/home/ash/internship_app/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 72, in enqueue
    enqueue(
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 208, in enqueue
    return enqueue_call()
           ^^^^^^^^^^^^^^
  File "/home/ash/internship_app/apps/frappe/frappe/utils/background_jobs.py", line 192, in enqueue_call
    return q.enqueue_call(
           ^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/queue.py", line 748, in enqueue_call
    return self.enqueue_job(job, pipeline=pipeline, at_front=at_front)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/queue.py", line 1147, in enqueue_job
    return self._enqueue_job(job, pipeline=pipeline, at_front=at_front)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/rq/queue.py", line 1180, in _enqueue_job
    pipe.execute()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1530, in execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 65, in call_with_retry
    fail(error)
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1532, in <lambda>
    lambda error: self._disconnect_raise_reset(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1508, in _disconnect_raise_reset
    raise error
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/retry.py", line 62, in call_with_retry
    return do()
           ^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1531, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1375, in _execute_transaction
    self.parse_response(connection, "_")
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 1462, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/client.py", line 584, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/connection.py", line 592, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 128, in read_response
    self.read_from_socket()
  File "/home/ash/internship_app/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 90, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
